version: "3"

services:
  web:
    build: "."
    command: yarn --cwd /app run start
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-host.docker.internal}/${POSTGRES_USER}
      - NUXT_PUBLIC_GITHUB_CLIENT_ID
      - NUXT_GITHUB_CLIENT_SECRET
      - NUXT_PUBLIC_GOOGLE_CLIENT_ID
      - NUXT_GOOGLE_CLIENT_SECRET
      - NUXT_SENDGRID_API_KEY
      - NUXT_SENDGRID_EMAIL
      - NUXT_AUTH_SECRET
      - AUTH_ORIGIN
      - NUXT_API_KEY_SECRET
      - NUXT_API_KEY_INIT_VECTOR
      - NUXT_SITE_NAME
      - NUXT_SITE_URL
      - NUXT_SITE_DESCRIPTION
      - NUXT_SITE_DEFAULT_LOCALE
      - NUXT_SITE_TWITTER
      # For uploading images
      - GOOGLE_PROJECT_ID
      - GOOGLE_BUCKET_ID
      # What port to serve on
      - PORT
    ports:
      - ${PORT:-3000}:${PORT:-3000}

    extra_hosts:
        - "host.docker.internal:host-gateway"
