version: "3"

services:
  web:
    build: "."
    command: yarn --cwd /app run start
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_USER}
      - NUXT_PUBLIC_GITHUB_CLIENT_ID
      - NUXT_GITHUB_CLIENT_SECRET
      - NUXT_PUBLIC_GOOGLE_CLIENT_ID
      - NUXT_GOOGLE_CLIENT_SECRET
      - NUXT_SENDGRID_API_KEY
      - NUXT_AUTH_SECRET
      - AUTH_ORIGIN
      - NUXT_API_KEY_SECRET
      - NUXT_API_KEY_INIT_VECTOR
      - NUXT_SITE_NAME
      - NUXT_SITE_URL
      # For uploading images
      - GOOGLE_PROJECT_ID
      - GOOGLE_BUCKET_ID
      - PORT
    ports:
      - ${PORT:-3000}:${PORT:-3000}
      - 5555:5555
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
